Omx Video encoder DIAF
I have ZERO motivation to fix this since I have never physcially seen a apq device.
I have no idea of the sequelae from removing this encoder, but choice 'B' is to remove all support for apq devices

 integer expressions [-Wsign-compare]
     if(profile_tbl[3] == m_eLevel)
                       ^
hardware/qcom/media-caf/msm8960/mm-video/vidc/venc/src/video_encoder_device.cpp: In member function 'bool venc_dev::venc_set_picture_order_count_type(OMX_U32)':
hardware/qcom/media-caf/msm8960/mm-video/vidc/venc/src/video_encoder_device.cpp:3320:3: error: 'venc_poctype' was not declared in this scope
   venc_poctype temp;
   ^
hardware/qcom/media-caf/msm8960/mm-video/vidc/venc/src/video_encoder_device.cpp:3321:32: error: 'temp' was not declared in this scope
   venc_ioctl_msg ioctl_msg = {&temp, NULL};
                                ^
hardware/qcom/media-caf/msm8960/mm-video/vidc/venc/src/video_encoder_device.cpp:3325:26: error: 'VEN_IOCTL_SET_PIC_ORDER_CNT_TYPE' was not declared in this scope
   if(ioctl(m_nDriver_fd, VEN_IOCTL_SET_PIC_ORDER_CNT_TYPE, (void *)&ioctl_msg) < 0)
                          ^
make: *** [/mnt/dho/L5/out/target/product/n1/obj/SHARED_LIBRARIES/libOmxVenc_intermediates/src/video_encoder_device.o] Error 1

Change-Id: Ic9b7b3ac3c17b0af4fad6a59fe3794af3d482ff8